volumes:
  prometheus: {}
services:
  proxy:
    build: ./requirements/proxy
    container_name: proxy_${PROJECT_NAME} #Proxy will get the "localhost.cert"
    image: proxy_${PROJECT_NAME}
    command: #Startup traefik cmd to populate the static conf
      - "--log.level=INFO" #Mode dispo : RACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.file.filename=/app/ssl.yml"
      - "--providers.docker.constraints=Label(`my.zone`, `${PROJECT_NAME}`)"
    labels:
      - "my.zone=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`${FQDN}`) && PathPrefix(`/dashboard`) || Host(`${FQDN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.middlewares.allow_all.ipallowlist.sourcerange=0.0.0.0/0"
      - "traefik.http.routers.api.middlewares=allow_all"
      - "traefik.http.routers.api.entrypoints=websecure"
    ports:
      # - "${PROJECT_PORT_ID}80:80" #Will be 80 when submiting
      - "${PROJECT_PORT_ID}81:443" #Will be 443 when submiting
      # - "${PROJECT_PORT_ID}82:8080" #Will be 8080 when submiting, used for traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #Docker sock, should work in the school
    env_file:
      - .env
    networks:
      default:
        aliases:
          - proxy
    restart: unless-stopped


  db:
    build: ./requirements/db
    container_name: db_${PROJECT_NAME} #Don't change it, its important for certificates, db will receive the "db.cert"
    image: db_${PROJECT_NAME}
    command: -c ssl=on -c ssl_cert_file=/ssl/db_${PROJECT_NAME}.crt -c ssl_key_file=/ssl/db_${PROJECT_NAME}.key
    env_file:
      - .env
    volumes: #Volumes binded should be changed before submiting the project
      - ./requirements/db/mount:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db
    restart: unless-stopped

  backend:
    build: ./requirements/backend
    container_name: backend_${PROJECT_NAME} #Don't change it, its important for certificates,  main_backend will receive the "main_db.cert"
    image: backend_${PROJECT_NAME}
    ports: #Expose port should be removed, the only authorize entrypoint for the front && backend will be the front throught the proxy
      - "${PROJECT_PORT_ID}80:8000"
    env_file:
      - .env
    volumes: #Volumes binded should be changed before submiting the project
      - ./requirements/backend/conf/mount:/usr/app
    depends_on:
      - db
    networks:
      default:
        aliases:
          - backend
    restart: unless-stopped

  frontend:
    build: ./requirements/frontend
    container_name: frontend_${PROJECT_NAME} #Don't change it, its important for certificates, frontend will receive the "frontend.cert"
    image: frontend_${PROJECT_NAME}
    # ports: #Expose port should be removed, the only authorize entrypoint for the front && backend will be the front throught the proxy
      # - "${PROJECT_PORT_ID}80:3000"
    labels: #Label used to dynamically conf traefik
      - "my.zone=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FQDN}`) && !PathPrefix(`/api{regex:/.*}`) && !PathPrefix(`/prometheus`)" #Do not trigger if its only /api... without any other /, to avoid trigger traefik api
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    env_file:
      - .env
    volumes: #Volumes binded should be changed before submiting the project
      - ./requirements/frontend/conf/mount:/app/src
    depends_on:
      - backend
      - proxy
    networks:
      default:
        aliases:
          - frontend
    restart: unless-stopped

##DevOps
  prometheus: #Prometheus is the metric collector used by Grafana
    build: ./requirements/prometheus
    container_name: prometheus_${PROJECT_NAME} #Don't change it, its important for certificates, frontend will receive the "frontend.cert"
    image: prometheus_${PROJECT_NAME}
    ports: #Expose port should be removed, the only authorize entrypoint for the front && backend will be the front throught the proxy
      - "9090:9090"
    labels: #Label used to dynamically conf traefik
      - "my.zone=${PROJECT_NAME}"
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.rule=Host(`${FQDN}`) && PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.services.prometheus.loadbalancer.server.scheme=https" #Communicate with the service in HTTPS
      - "traefik.http.services.prometheus.loadbalancer.serverstransport=transport_prometheus@file"
    env_file:
      - .env
    volumes: #Volume not binded OK
      - prometheus:/prometheus
    depends_on:
      - backend
      - proxy
    networks:
      default:
        aliases:
          - prometheus
    restart: unless-stopped