version: '3'

services:
  backend:
    build: ./requirements/backend
    container_name: backend
    image: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    #depends_on:
      #- db
    #networks:
      #- backend
    restart: unless-stopped

#  db:
#    container_name: db
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    env_file:
#      - .env
#    environment:
#      TZ: "Europe/Paris"
#    volumes:
#      - data:/var/lib/postgresql/data
#    networks:
#      - backend
#    restart: unless-stopped

#volumes:
#  v_db:

#networks:
#  backend:
#    driver: bridge