services:
  db:
    container_name: db
    image: postgres:14.11
    env_file:
      - .env
    volumes:
      - ./requirements/db:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./requirements/backend
    container_name: backend
    image: backend
#    Changez le 3eme chiffre du 1er port selon la personne
#    1 greg 2 theo 3 melanie 4 benjamin 5 noe
    ports:
      - "50280:8000"
    env_file:
      - .env
    volumes:
      - ./requirements/backend/conf/mount:/usr/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./requirements/frontend
    container_name: frontend
    image: frontend
#    Changez le 3eme chiffre du 1er port selon la personne
#    1 greg 2 theo 3 melanie 4 benjamin 5 noe
    ports:
      - "50281:3000"
    env_file:
      - .env
    volumes:
      - ./requirements/frontend/conf/mount:/app/src
    depends_on:
      - backend
    restart: unless-stopped
