global:
  scrape_interval:     5s # By default
rule_files:
  - /etc/prometheus/alerts-rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
scrape_configs:
  - job_name: 'traefik'
    scheme: https
    metrics_path: /adm/metrics
    static_configs:
      - targets: ['proxy:443']