{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Proxy specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy Requests",
   "type": "piechart",
   "description": "All request to proxy",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (traefik_service_requests_total)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connections to entrypoints",
   "type": "piechart",
   "description": "Activity of:\nWeb (HTTP:80) port\nWebsecure (HTTPS:443) port\nWebsocket(HTTPS:4433) port",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_open_connections{entrypoint!=\"traefik\"}",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up[1d]) * 100 / (1 * 24 * 60)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requested",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (traefik_service_requests_bytes_total)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}