# Generated by Django 4.2.11 on 2024-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_join_date_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='male',
            field=models.BooleanField(null=True),
        ),
    ]
